github actions update (#21)

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -15,35 +15,34 @@ on:
     branches:
       - main
 jobs:
-
   test:
     runs-on: ubuntu-latest
     timeout-minutes: 30
 
     steps:
-    - uses: actions/checkout@v2
-      with:
-        submodules: recursive
-        fetch-depth: 0
+      - uses: actions/checkout@v3
+        with:
+          submodules: recursive
+          fetch-depth: 0
 
-    - name: Building tests
-      run: docker build . --file DockerTestFile --tag petsc-xdmf-generator-test-image
+      - name: Building tests
+        run: docker build . --file DockerTestFile --tag petsc-xdmf-generator-test-image
 
-    - name: Get the version from the build file
-      run: echo "VERSION=$(docker run --rm petsc-xdmf-generator-test-image awk -F= '/CMAKE_PROJECT_VERSION:/ {print $NF}' CMakeCache.txt )" >> $GITHUB_ENV
+      - name: Get the version from the build file
+        run: echo "VERSION=$(docker run --rm petsc-xdmf-generator-test-image awk -F= '/CMAKE_PROJECT_VERSION:/ {print $NF}' CMakeCache.txt )" >> $GITHUB_ENV
 
-    - name: Check for version
-      run: |
-        echo "Checking version: v$VERSION"
-        if git rev-parse "v$VERSION" >/dev/null 2>&1; then
-          echo "::error file=CMakeLists.txt::The version already exists!"
-          exit 1
-        else
-          echo "version does not exist"
-        fi
+      - name: Check for version
+        run: |
+          echo "Checking version: v$VERSION"
+          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
+            echo "::error file=CMakeLists.txt::The version already exists!"
+            exit 1
+          else
+            echo "version does not exist"
+          fi
 
-    - name: Run tests
-      run: docker run --rm petsc-xdmf-generator-test-image
+      - name: Run tests
+        run: docker run --rm petsc-xdmf-generator-test-image
 
   tag-version:
     # Ensure test job passes before pushing image.
@@ -53,7 +52,7 @@ jobs:
     if: github.event_name == 'push'
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           submodules: recursive
 
@@ -65,7 +64,7 @@ jobs:
 
       - name: set version and push tag
         id: tag_version
-        uses: mathieudutour/github-tag-action@v5
+        uses: mathieudutour/github-tag-action@v6.1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           custom_tag: ${{env.VERSION}}
